import appName from '@/constants/settings';
const pdfDownloader = async (content: string) => {
  // Dynamically import html2pdf.js
  const html2pdf = (await import('html2pdf.js')).default;

  // Create a container for the content
  const element = document.createElement('div');
    element.innerHTML = content;
    element.style.padding = "20px";
  // Define options for the PDF
  const footer = document.createElement('footer');
    footer.style.borderTop = "2px dashed #000";
    footer.style.paddingBlock = "10px";
    footer.style.textAlign = "center";
    footer.style.marginTop = "50px";
    footer.innerHTML = `Generated by <b style='color:red;'>${appName}</b> on  ${new Date().toLocaleDateString()}`;
    element.appendChild(footer);
  const options = {
    margin: 1,
    filename: 'mewtron.pdf',
    image: { type: 'jpeg', quality: 0.98 },
    html2canvas: { scale: 2 },
    jsPDF: { unit: 'in', format: 'letter', orientation: 'portrait' },
  };

  // Generate and save the PDF
  html2pdf().set(options).from(element).save();
};

export default pdfDownloader;
